services:
  db:
    image: postgres:15
    container_name: hatchapp_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password # Tells Postgres to read password from this file
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Change host port to 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password
    networks:
      - hatch-network


# Top-level secrets definition
secrets:
  pg_password:
    file: ./.secrets/POSTGRES_PASSWORD
  mongo_password:
    file: ./.secrets/MONGO_PASSWORD
  influx_token:
    file: ./.secrets/INFLUX_TOKEN
  influx_password:
    file: ./.secrets/INFLUXDB_PASSWORD

volumes:
  pgdata:
  mongo_data:
  influxdb_data:

networks:
  hatch-network:
    driver: bridge
      